### ISSUE TITLE
Not an Issue -- Do this please

### ISSUE THREAD

**Issue by Arch881010** [amiantos/rpg-laravel#1]
This sounds like another RPG that could blow up.

Would like to have you added it to where the website is so we could access it while watching this get worked on!

**Comment by amiantos** [comment]
Thanks for your enthusiasm! I had a lot of fun building the basics of this on stream, and the videos are on YouTube I think, but I bounced off streaming and this project unfortunately.

**Comment by Arch881010** [comment]
I suppose I shall use this to understand web games as a basis.
Need to learn PHP myself anyway!

**Comment by amiantos** [comment]
Laravel is a lot of fun, great way to learn PHP. But I'd also recommend starting off writing some basic PHP scripts without a framework like Laravel. I don't have any learning recommendations off the top of my head, but PHP is so widespread and widely used you can basically find good stuff anywhere.
